### ISSUE TITLE
byte-buddy-maven-plugin fails if packaging is "pom"

### ISSUE THREAD

**Issue by DiabolusExMachina** [raphw/byte-buddy#310]
Hi, first thanks for this awesome library!
However I'm having some trouble with the maven plugin:   

I have a multi module project and want to apply a transformation on all child modules. Because of that I put the plugin config in the parent module with packaging pom. But now the build of this parent module fails because the byte-buddy-maven-plugin tries to apply the transformations but cannot find any classes

> Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.6.9:transform (default) on project oraservices: Target location does not exist or is no directory: path/to/non/existing/classes/folder/of/pom/project

Is there any other way to apply a transformation to all child modules beside put the config in every child pom file? 

my config in parent pom looks like this: 

```
<build>
    <plugins>
      <plugin>
        <groupId>net.bytebuddy</groupId>
        <artifactId>byte-buddy-maven-plugin</artifactId>
        <version>${byte-buddy.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>transform</goal>
              <goal>transform-test</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <transformations>
            <transformation>
              <plugin>classname</plugin>
              <groupId>my.group.id</groupId>
              <artifactId>my.artifact.id</artifactId>
              <version>my.version</version>
            </transformation>
          </transformations>
        </configuration>
      </plugin>
    </plugins>
<build>
```

**Comment by raphw** [comment]
Glad you like the library.

I just updated the plugin. Could you do me a favour and clone the repository, build Byte Buddy and try the snapshot version against your project. Otherwise, I will do it myself but would first need to create a project to do so what can take a few days until I find the time.

**Comment by DiabolusExMachina** [comment]
Yes this problem is gone. Thank you!

However my build is still fails because some of the child projects do not have Unit Tests and I got this error: 

> [ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.7.1-SNAPSHOT:transform-test (default) on project oraserv_account: Target location does not exist or is no directory: path/to/non/existing/test-classes/folder/of/test-classes -> [Help 1]

Do you think a warning that nothing can be transformed would be enough or do you want the build to break in such cases?

**Comment by raphw** [comment]
I can make it configurable and issue a warning by default unless  non-existing folders are explicitly disabled. Thanks for the feedback!

**Comment by DiabolusExMachina** [comment]
Great thanks again!

**Comment by raphw** [comment]
I reworked the plugin. Can you try again?

**Comment by DiabolusExMachina** [comment]
Yes. It works as expected!

**Comment by raphw** [comment]
Fixed on master, will be part of the next release.
